version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - hehe_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - hehe_static:/data/static/
      - hehe_media:/data/media/

  django:
    image: hehe:3
    networks:
      - hehe_network
    volumes:
      - hehe_static:/home/gis_django/staticfiles/
      - hehe_media:/home/gis_django/media/

networks:
  hehe_network:

volumes:
  hehe_static:
  hehe_media: